/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smqa_project;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collections;
import javafx.print.Collation;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sun.java2d.loops.Blit;

/**
 *
 * @author Mesut
 */
public class Anasayfa extends javax.swing.JFrame {
  ArrayList<Urunler> lst=new ArrayList<Urunler>();
  ArrayList<Stok> lststok=new ArrayList<Stok>();
  ArrayList<Stok> lstsatis=new ArrayList<Stok>();
    public Anasayfa() {
        initComponents();
       churunler.removeAllItems(); // ürünsil 
       churunler1.removeAllItems(); // rakam olarak fiyat güncelle
       churunler2.removeAllItems(); //yüzde olarak fiyat güncelle
       churunler3.removeAllItems(); // stok işlemleri
       chstokdus.removeAllItems(); //stok işlemleri
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnurunmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnstokmenu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnkazancrapormenu = new javax.swing.JButton();
        Jpurun = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnkaydet = new javax.swing.JButton();
        txturunad = new javax.swing.JTextField();
        txtfiyat = new javax.swing.JTextField();
        churunler = new javax.swing.JComboBox<>();
        btnsil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnguncelle1 = new javax.swing.JButton();
        txtfiyat1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        churunler1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        churunler2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnguncelle = new javax.swing.JButton();
        txtfiyat2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnprogram = new javax.swing.JButton();
        jpstok = new javax.swing.JPanel();
        churunler3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtstokgir = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnstokgir = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btnstokdus = new javax.swing.JButton();
        txtstokdus = new javax.swing.JTextField();
        chstokdus = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtstokmaliyet = new javax.swing.JTextField();
        list2 = new java.awt.List();
        jprapor = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        list3 = new java.awt.List();
        list4 = new java.awt.List();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnurunmenu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnurunmenu.setForeground(new java.awt.Color(255, 0, 51));
        btnurunmenu.setText("Ürün İşlemleri");
        btnurunmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnurunmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnurunmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnurunmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnstokmenu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnstokmenu.setForeground(new java.awt.Color(255, 0, 51));
        btnstokmenu.setText("Stok İşlemleri");
        btnstokmenu.setPreferredSize(new java.awt.Dimension(101, 23));
        btnstokmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstokmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(btnstokmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnstokmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnkazancrapormenu.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnkazancrapormenu.setForeground(new java.awt.Color(255, 0, 51));
        btnkazancrapormenu.setText("Kazanç / Kayıp Raporu");
        btnkazancrapormenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkazancrapormenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnkazancrapormenu, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnkazancrapormenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jpurun.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Ürün Adı:");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Fiyatı:");

        btnkaydet.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnkaydet.setText("Kaydet");
        btnkaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkaydetActionPerformed(evt);
            }
        });

        txturunad.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        txtfiyat.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        churunler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnsil.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnsil.setText("Sil");
        btnsil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsilActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Ürün Adı:");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Fiyatı:");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Ürün Adı");

        btnguncelle1.setText("Güncelle");
        btnguncelle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelle1ActionPerformed(evt);
            }
        });

        txtfiyat1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setText("Fiyatı:");

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setText("Ürün Adı");

        churunler1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setText("Yüzde Olarak Fiyat Güncelle");

        churunler2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setText("Rakam Olarak Fiyat Güncelle");

        btnguncelle.setText("Güncelle");
        btnguncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguncelleActionPerformed(evt);
            }
        });

        txtfiyat2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setText("Ürün Sil");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setText("Ürün Ekle");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setText("Ürün Listesi");

        javax.swing.GroupLayout JpurunLayout = new javax.swing.GroupLayout(Jpurun);
        Jpurun.setLayout(JpurunLayout);
        JpurunLayout.setHorizontalGroup(
            JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpurunLayout.createSequentialGroup()
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(38, 38, 38)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel12))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txturunad, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(btnsil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(churunler, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfiyat2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(churunler2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JpurunLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(10, 10, 10)
                            .addComponent(churunler1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JpurunLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(24, 24, 24)
                            .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfiyat1)
                                .addGroup(JpurunLayout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(btnguncelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpurunLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(17, 17, 17)))
                .addGap(68, 68, 68))
            .addGroup(JpurunLayout.createSequentialGroup()
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpurunLayout.setVerticalGroup(
            JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpurunLayout.createSequentialGroup()
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(churunler1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(txtfiyat1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnguncelle1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(churunler2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(34, 34, 34)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtfiyat2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnguncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpurunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnsil, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(churunler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(JpurunLayout.createSequentialGroup()
                        .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpurunLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(JpurunLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(JpurunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txturunad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnprogram.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnprogram.setForeground(new java.awt.Color(255, 0, 51));
        btnprogram.setText("Program Hakkında");
        btnprogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprogramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnprogram, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnprogram, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpstok.setBackground(new java.awt.Color(153, 255, 255));
        jpstok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        churunler3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setText("Ürün Adı");

        txtstokgir.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setText("Stok Ekle");

        btnstokgir.setText("Ekle");
        btnstokgir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstokgirActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setText("Stok Gir");

        btnstokdus.setText("Ekle");
        btnstokdus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstokdusActionPerformed(evt);
            }
        });

        txtstokdus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        chstokdus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel17.setText("Stok Düş");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel18.setText("Ürün Adı");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel19.setText("Stok");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel20.setText("Stok Listesi");

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel24.setText("Maliyet");

        txtstokmaliyet.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        javax.swing.GroupLayout jpstokLayout = new javax.swing.GroupLayout(jpstok);
        jpstok.setLayout(jpstokLayout);
        jpstokLayout.setHorizontalGroup(
            jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstokLayout.createSequentialGroup()
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(churunler3, 0, 177, Short.MAX_VALUE)
                            .addComponent(txtstokgir)))
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnstokgir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpstokLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(txtstokmaliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chstokdus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtstokdus, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnstokdus, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpstokLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel17)))
                .addGap(62, 62, 62)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpstokLayout.setVerticalGroup(
            jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpstokLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(churunler3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstokgir, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstokmaliyet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnstokgir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpstokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(chstokdus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jpstokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstokdus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnstokdus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpstokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jprapor.setBackground(new java.awt.Color(153, 255, 153));
        jprapor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel21.setText("Satışlar");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel22.setText("Mevcut Durum");

        javax.swing.GroupLayout jpraporLayout = new javax.swing.GroupLayout(jprapor);
        jprapor.setLayout(jpraporLayout);
        jpraporLayout.setHorizontalGroup(
            jpraporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpraporLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpraporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpraporLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(409, 409, 409)
                        .addComponent(jLabel22))
                    .addGroup(jpraporLayout.createSequentialGroup()
                        .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpraporLayout.setVerticalGroup(
            jpraporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpraporLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpraporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addGap(26, 26, 26)
                .addGroup(jpraporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel23.setText("İstanbul Ticaret Üniversitesi Bilgisayar Mühendisliği Tezli Yüksek Lisans Programı Ders projesi olarak yapılmıştır. ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel23)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpstok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jpurun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jprapor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(Jpurun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jprapor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        Jpurun.getAccessibleContext().setAccessibleName("");
        Jpurun.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnurunmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnurunmenuActionPerformed
      // TODO add your handling code here: 
        if (Jpurun.isVisible()) {
            Jpurun.setVisible(false);
        }
        else{
        Jpurun.setVisible(true);
        jpstok.setVisible(false);
        jprapor.setVisible(false);
        }      
    }//GEN-LAST:event_btnurunmenuActionPerformed

    private void btnstokmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstokmenuActionPerformed
        // TODO add your handling code here:
       if (jpstok.isVisible()) {
           jpstok.setVisible(false);
        }
        else{
        jpstok.setVisible(true);
        Jpurun.setVisible(false); 
        jprapor.setVisible(false);
        }    
    }//GEN-LAST:event_btnstokmenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Jpurun.setVisible(false);
        jpstok.setVisible(false);
        jprapor.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnkazancrapormenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkazancrapormenuActionPerformed
        // TODO add your handling code here:
        if (jprapor.isVisible()) {
            jprapor.setVisible(false);
            stoklistele(); 
        }
        else{
        jprapor.setVisible(true);   
        Jpurun.setVisible(false);
        jpstok.setVisible(false); 
        }   
    }//GEN-LAST:event_btnkazancrapormenuActionPerformed
 
    private void btnprogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprogramActionPerformed
        // TODO add your handling code here:
        Jpurun.setVisible(false);
        jpstok.setVisible(false);
        jprapor.setVisible(false);
    }//GEN-LAST:event_btnprogramActionPerformed

    private void btnguncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelleActionPerformed
        // TODO add your handling code here:
        String d=churunler2.getSelectedItem().toString();
        for(Urunler u:lst){
            String a=u.ad;

            if( d == null ? a == null : d.equals(a))
            {
                Urunler ul=new Urunler();
                ul.ID=u.ID;
                ul.ad=u.ad;
                ul.fiyat=u.fiyat*Double.parseDouble(txtfiyat2.getText())/100;
                lst.remove(u);
                lst.add(ul);
                JOptionPane.showMessageDialog(null,"Güncellendi",
                    "Uyarı", JOptionPane.CLOSED_OPTION);
            }

        }
        listele();
        //txtfiyat2
    }//GEN-LAST:event_btnguncelleActionPerformed

    private void btnguncelle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguncelle1ActionPerformed
        // TODO add your handling code here:
        String d=churunler2.getSelectedItem().toString();
        for(Urunler u:lst){
            String a=u.ad;

            if( d == null ? a == null : d.equals(a))
            {
                Urunler ul=new Urunler();
                ul.ID=u.ID;
                ul.ad=u.ad;
                ul.fiyat=Double.parseDouble(txtfiyat2.getText());
                lst.remove(u);
                lst.add(ul);
                JOptionPane.showMessageDialog(null,"Güncellendi",
                    "Uyarı", JOptionPane.CLOSED_OPTION);
            }

        }
        listele();
    }//GEN-LAST:event_btnguncelle1ActionPerformed

    private void btnkaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkaydetActionPerformed
        // TODO add your handling code here:
        Urunler yeni = new Urunler();
        int id=0;
        for(int i=0;i<lst.size();i++){
            int d=lst.get(i).ID;
            if (id<d) {
                id=d;
            }
        }
        int bayrak=0;
        String d=txturunad.getText();
        for(Urunler u:lst){ 
            String a=u.ad;
            if( d == null ? a == null : d.equals(a))
            bayrak=1; 
        }
        if (bayrak==0) {
            id=id+1;
            yeni.ad=txturunad.getText();
            yeni.fiyat=Double.parseDouble(txtfiyat.getText());
            yeni.ID=id;
            lst.add(yeni);
            churunler.addItem(yeni.ad);
            churunler1.addItem(yeni.ad);
            churunler2.addItem(yeni.ad);
            churunler3.addItem(yeni.ad);
            chstokdus.addItem(yeni.ad);
            listele();
            /*
            churunler.removeAllItems(); // ürünsil
            churunler1.removeAllItems(); // rakam olarak fiyat güncelle
            churunler2.removeAllItems(); //yüzde olarak fiyat güncelle
            */
        }
        //jList1.setListData((String[]) lst.toArray());
    }//GEN-LAST:event_btnkaydetActionPerformed

    private void btnstokgirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstokgirActionPerformed
        // TODO add your handling code here:
       Stok yeni = new Stok();
       int id=0;
       String d=churunler3.getSelectedItem().toString();
       int bayrak=0;
       int a = 0;
       int var=0; 
       int sayac=0;
       int sayac2=0;
       for(Urunler ne:lst){ 
                  if (ne.ad.equals(d)) {
                      a=ne.ID;                              
                  }
       }
       for(Stok u:lststok){  
             sayac+=1;  
           if (u.Urunno==a) {
                  var=1;
                  sayac2=sayac;
                yeni.Urunno=a;
                yeni.cost=Integer.parseInt(txtstokmaliyet.getText());
                yeni.item+=Integer.parseInt(txtstokgir.getText());
                lststok.remove(u);
                lststok.add(yeni);
              } 
              
           }
        if (var==0) {
                yeni.Urunno=a;
                yeni.cost=Integer.parseInt(txtstokmaliyet.getText());
                yeni.item =Integer.parseInt(txtstokgir.getText()); 
                lststok.add(yeni);
        }
     
        stoklistele(); 
    }//GEN-LAST:event_btnstokgirActionPerformed

    private void btnstokdusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstokdusActionPerformed
        // TODO add your handling code here: 
       Stok yeni = new Stok();
       Stok satis = new Stok();
       int id=0;
       double fiyat=0;
       int adet=0;
       String d=chstokdus.getSelectedItem().toString();
       int bayrak=0;
       int a = 0;
       int var=0; 
       int sayac=0;
       int sayac2=0;
       for(Urunler ne:lst){ 
                  if (ne.ad.equals(d)) {
                      a=ne.ID;   
                  }
       }
       for(Stok u:lststok){  
             sayac+=1;  
           if (u.Urunno==a) {
                var=1;
                fiyat=u.cost;
                adet=u.item;
                sayac2=sayac;
                    if (adet>=Double.parseDouble(txtstokdus.getText())) {
                           yeni.Urunno=a;
                           yeni.cost=fiyat;
                           yeni.item=adet-Integer.parseInt(txtstokdus.getText());
                          lststok.remove(u);
                          lststok.add(yeni);  
                          satis.Urunno=a;
                          satis.cost=fiyat;
                          satis.item=Integer.parseInt(txtstokdus.getText());
                          lstsatis.add(satis);
                        }
                    else{
                           JOptionPane.showMessageDialog(null,"Adetten fazla stoktan düşülemez",
                           "Uyarı", JOptionPane.CLOSED_OPTION);
                        }
             } 
              
           }
    
          
             
         stoklistele();
    }//GEN-LAST:event_btnstokdusActionPerformed

    private void btnsilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsilActionPerformed
            // TODO add your handling code here:
       Stok yeni = new Stok(); 
       String d=churunler.getSelectedItem().toString();
       int bayrak=0;
       int a = 0;
       int var=0; 
       int sayac=0;
       int sayac2=0;
       for(Urunler ne:lst){ 
                  if (ne.ad.equals(d)) {
                      a=ne.ID;   
                  }
       }
       for(Stok u:lststok){  
             sayac+=1;  
           if (u.Urunno==a) {
                  var=1;
                
              } 
              
           }
        if (var==1) {
              JOptionPane.showMessageDialog(null,"Stokta ürün mevcut silinemez",
                    "Uyarı", JOptionPane.CLOSED_OPTION);
        }
        else{
            
            for(Urunler ne:lst){ 
                  if (ne.ad.equals(d)) {
                      a=ne.ID;  
                      lst.remove(ne);
                      listele();  
                      JOptionPane.showMessageDialog(null,"Ürün silindi",
                    "Uyarı", JOptionPane.CLOSED_OPTION);
                      int index=churunler.getSelectedIndex();
                      churunler.removeItemAt(index); // ürünsil 
                      churunler1.removeItemAt(index); // rakam olarak fiyat güncelle
                      churunler2.removeItemAt(index); //yüzde olarak fiyat güncelle
                      churunler3.removeItemAt(index); // stok işlemleri
                      chstokdus.removeItemAt(index); //stok işlemleri
                  }
                }
             }
       
    
    }//GEN-LAST:event_btnsilActionPerformed
    public void listele(){
    //list1 ürünler
     list1.removeAll();
     for(Urunler u:lst){ 
         String a="Ad:"+u.ad+" ID:"+String.valueOf(u.ID)+"fiyat:"+String.valueOf(u.fiyat);  
         list1.add(a);
        }
    
    }
  public void stoklistele(){
    //list1 ürünler
     list2.removeAll();
     list3.removeAll();
     list4.removeAll();
     for(Stok u:lststok){ 
         String a="Ürün no:"+u.Urunno+" Adet: "+String.valueOf(u.item)+" fiyat: "+String.valueOf(u.cost);  
         list2.add(a); // stok işlemleri
         list4.add(a);//mevcut durum kazanç raporu
        }
   
    for(Stok u:lstsatis){ 
         String a="Ürün no:"+u.Urunno+" Adet: "+String.valueOf(u.item)+" fiyat: "+String.valueOf(u.cost);  
         list3.add(a); // stok işlemleri 
        }
    }
    /**
     * @param args the command line arguments
     */
      
      
    public static void main(String args[]) {
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anasayfa().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpurun;
    private javax.swing.JButton btnguncelle;
    private javax.swing.JButton btnguncelle1;
    private javax.swing.JButton btnkaydet;
    private javax.swing.JButton btnkazancrapormenu;
    private javax.swing.JButton btnprogram;
    private javax.swing.JButton btnsil;
    private javax.swing.JButton btnstokdus;
    private javax.swing.JButton btnstokgir;
    private javax.swing.JButton btnstokmenu;
    private javax.swing.JButton btnurunmenu;
    private javax.swing.JComboBox<String> chstokdus;
    private javax.swing.JComboBox<String> churunler;
    private javax.swing.JComboBox<String> churunler1;
    private javax.swing.JComboBox<String> churunler2;
    private javax.swing.JComboBox<String> churunler3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jprapor;
    private javax.swing.JPanel jpstok;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.List list3;
    private java.awt.List list4;
    private javax.swing.JTextField txtfiyat;
    private javax.swing.JTextField txtfiyat1;
    private javax.swing.JTextField txtfiyat2;
    private javax.swing.JTextField txtstokdus;
    private javax.swing.JTextField txtstokgir;
    private javax.swing.JTextField txtstokmaliyet;
    private javax.swing.JTextField txturunad;
    // End of variables declaration//GEN-END:variables

   
}
